version: '3'
volumes:
  psql-data:
services:
  app:
    build: .
    command: bash -c "rm ./tmp/pids/server.pid; bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/woodmister
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:10
    volumes:
      - psql-data:/var/lib/postgresql/data

