version: '3'
volumes:
  psql-data:
  redis-data:
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/woodmister
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - sidekiq
  sidekiq:
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/woodmister
    depends_on:
      - redis
  postgres:
    image: postgres:10
    volumes:
      - psql-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
