app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - ./:/woodmister
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:10
  ports:
    - "5432"
  volumes:
    - woodmister-postgresql:/var/lib/postgresql/data
