default: &default
  adapter: postgresql 
  encoding: unicode 
  pool: 5 
  timeout: 5000 
  username: pixelgoo
  password: vjkjrj87 
  host: localhost
  port: 5432

development:
  <<: *default
  database: furniture_development

test:
  <<: *default
  database: furniture_development_test

production:
  <<: *default
